const {
    OVERFLOW_MORE_OPTIONS_SELECTORS,
    OVERFLOW_SAVE_MENU_SELECTORS
} = require('./overflow_save_flow');

const FINANCIAL_FEATURES_MORE_OPTIONS_SELECTORS = OVERFLOW_MORE_OPTIONS_SELECTORS;
const FINANCIAL_FEATURES_SAVE_MENU_SELECTORS = OVERFLOW_SAVE_MENU_SELECTORS;

module.exports = {
    FINANCIAL_FEATURES_MORE_OPTIONS_SELECTORS,
    FINANCIAL_FEATURES_SAVE_MENU_SELECTORS
};
